### ISSUE TITLE
Simple way to parse address from a string

### ISSUE THREAD

**Issue by simonthemagico** [alannadevgen/french-address-matching#18]
Example : 

- input : Adresse postale, 8 BD DUBREUIL 91400 ORSAY ; Numéros d'identification ; Numéro SIREN ; Numéro SIRET (siège) ; Numéro TVA Intracommunautaire.

- output : 8 BD DUBREUIL 91400 ORSAY (or other format)

**Comment by aldevgen** [comment]
I don't understand what you're trying to say.
